'use client';

import React, { useState } from 'react';
import type { MeetingSummary } from '@/types/database';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { toast } from 'sonner';
import { ThumbsUp, ThumbsDown, Sparkles, Check } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';

import { logger } from '@/lib/logger';

interface AISummaryCardProps {
  summary: MeetingSummary;
  meetingId: string;
}

export function AISummaryCard({ summary, meetingId }: AISummaryCardProps) {
  const [feedback, setFeedback] = useState<'thumbs_up' | 'thumbs_down' | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [selectedCategories, setSelectedCategories] = useState<string[]>([]);
  const [submitting, setSubmitting] = useState(false);

  const handleThumbsUp = async () => {
    if (feedback === 'thumbs_up') return;
    setFeedback('thumbs_up');
    setShowForm(false);
    
    try {
      const res = await fetch('/api/feedback', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          entity_type: 'summary',
          entity_id: meetingId,
          feedback: 'thumbs_up',
        }),
      });
      if (res.ok) {
        toast.success('Thanks for your feedback! 👍');
      }
    } catch (err) {
      logger.error('Failed to submit thumbs up:', err);
    }
  };

  const handleThumbsDown = () => {
    setFeedback('thumbs_down');
    setShowForm(true);
  };

  const toggleCategory = (category: string) => {
    setSelectedCategories((prev) =>
      prev.includes(category) ? prev.filter((c) => c !== category) : [...prev, category]
    );
  };

  const submitFeedbackForm = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);
    try {
      const res = await fetch('/api/feedback', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          entity_type: 'summary',
          entity_id: meetingId,
          feedback: 'thumbs_down',
          categories: selectedCategories,
        }),
      });

      if (res.ok) {
        toast.success('Thanks, this helps improve MeetIQ');
        setShowForm(false);
      } else {
        toast.error('Failed to save feedback');
      }
    } catch (err) {
      logger.error("Error occurred", err);
      toast.error('Error saving feedback');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Card className="ai-card shadow-meetiq-xs overflow-hidden">
      <CardContent className="p-8 space-y-5">
        {/* Header */}
        <div className="flex items-center justify-between gap-2 border-b border-blue-100 pb-4">
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger render={<div className="flex items-center gap-1.5 cursor-help" />}>
                <Sparkles className="h-4 w-4 text-blue-600" />
                <span className="ai-label">AI Generated Summary</span>
              </TooltipTrigger>
              <TooltipContent className="bg-white text-primary border border-meetiq-border/5 shadow-meetiq-sm p-2 text-xs">
                This summary was generated by AI. Please review for accuracy.
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>

          {/* Confidence Badge */}
          <div className="flex items-center gap-1.5">
            <span className="text-sm font-medium text-emerald-700 bg-emerald-50 px-4 rounded-full border border-emerald-100 h-[30px] inline-flex items-center">
              High Confidence
            </span>
          </div>
        </div>

        {/* Content */}
        <div className="space-y-3 font-body text-sm leading-relaxed text-slate-800">
          <ul className="list-disc pl-5 space-y-3">
            {summary?.bullets.map((bullet, idx) => (
              <li key={idx}>{bullet}</li>
            ))}
          </ul>
        </div>

        {/* Footer actions */}
        <div className="flex items-center justify-between pt-4 border-t border-blue-50">
          <span className="text-xs text-muted-foreground italic">
            AI-generated content may require human review.
          </span>
          <div className="flex items-center gap-1.5">
            <Button
              variant="ghost"
              size="icon"
              className={`h-8 w-8 text-slate-400 hover:text-emerald-600 hover:bg-emerald-50 ${feedback === 'thumbs_up' ? 'text-emerald-600 bg-emerald-50' : ''}`}
              onClick={handleThumbsUp}
            >
              <ThumbsUp className="h-4 w-4" />
            </Button>
            <Button
              variant="ghost"
              size="icon"
              className={`h-8 w-8 text-slate-400 hover:text-red-600 hover:bg-red-50 ${feedback === 'thumbs_down' ? 'text-red-600 bg-red-50' : ''}`}
              onClick={handleThumbsDown}
            >
              <ThumbsDown className="h-4 w-4" />
            </Button>
          </div>
        </div>

        {/* Feedback categories form */}
        {showForm && (
          <form onSubmit={submitFeedbackForm} className="border-t border-dashed border-blue-200/50 pt-4 mt-2 space-y-3 bg-white p-4 rounded-lg border">
            <p className="text-xs font-semibold text-primary">What needs improvement?</p>
            <div className="grid grid-cols-2 gap-2">
              {['Summary bullets', 'Tone/Style', 'Missing topics', 'Accuracy', 'Other'].map((category) => (
                <div key={category} className="flex items-center space-x-2">
                  <Checkbox
                    id={`summary-cat-${category}`}
                    checked={selectedCategories.includes(category)}
                    onCheckedChange={() => toggleCategory(category)}
                  />
                  <Label
                    htmlFor={`summary-cat-${category}`}
                    className="text-xs font-normal text-slate-600 cursor-pointer"
                  >
                    {category}
                  </Label>
                </div>
              ))}
            </div>
            <div className="flex justify-end gap-2 pt-2">
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={() => setShowForm(false)}
                className="h-8 text-xs"
              >
                Cancel
              </Button>
              <Button type="submit" size="sm" className="h-8 text-xs" disabled={submitting}>
                {submitting ? 'Submitting...' : 'Submit feedback'}
              </Button>
            </div>
          </form>
        )}
      </CardContent>
    </Card>
  );
}
